name: Publish Pre-check

on: [push, pull_request]

jobs:
  testVerdaccio:
    name: Test Verdaccio Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # node
    - name: Use Node.js 20.x
      uses: actions/setup-node@v1
      with:
        node-version: 20.x
    - name: Install verdaccio
      run: npm install -g verdaccio
    - name: Prepare verdaccio config
      run: |
        mkdir storage
        echo "storage: ./storage" > verdaccio.yml
        echo "packages:" >> verdaccio.yml
        echo "  '**':" >> verdaccio.yml
        echo '    access: $all' >> verdaccio.yml
        echo '    publish: $all' >> verdaccio.yml
        echo '    unpublish: $all' >> verdaccio.yml
        echo '    proxy: npmjs' >> verdaccio.yml
    - name: Start verdaccio
      run: verdaccio --config verdaccio.yml &
    - name: Publish package in verdaccio
      run: npm publish --registry http://localhost:4873
