name: Publish Pre-check

on: [push, pull_request]

jobs:
  testVerdaccio:
    name: Test Verdaccio Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Publish
      uses: verdaccio/github-actions/publish@v0.1.0
      with:
        args: -d
